-- AlterTable
ALTER TABLE "Fill" ALTER COLUMN "quantity" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "fee" SET DATA TYPE DOUBLE PRECISION;

-- DropEnum
DROP TYPE "PositionStatus";
